.github/workflows/test.yml

because this repository was mentioned here:
https://github.com/hugovk/pypistats/issues/181

Replace 3.9-dev with 3.9 in CI to use Python 3.9 final

---

.pre-commit-config.yaml
setup.cfg
setup.py
src/termcolor/__init__.py
src/termcolor/termcolor.py
tests/test_termcolor.py

This helps library consumers ensure that they are using the provided API
correctly. The project includes a py.typed file for PEP-561 compliance.
This also helps ensure internal correctness and consistency. mypy also
runs on the tests, to demonstrate the test cases are representative and
real use cases.
Type checking will run on all pull requests through GitHub actions and
pre-commit.

Add type annotations to the project and run mypy on CI

---

src/termcolor/termcolor.py

The docstring for the function `colored` was missing the color `grey` and the highlight `on_grey`. The example used the non existing attribute `blue`. This has been replaced by `bold`.

Fix docstring for colored function

---

src/termcolor/__init__.py
src/termcolor/termcolor.py

To find the version, use:
```python
try:
import importlib.metadata as importlib_metadata
except ImportError:
import importlib_metadata
print(importlib_metadata.version("termcolor"))
```
Docs: https://docs.python.org/3/library/importlib.metadata.html#distribution-versions
Backport: https://pypi.org/project/importlib-metadata/

Remove hardcoded VERSION constant

---

.github/workflows/deploy.yml
RELEASING.md

Using https://github.com/pypa/gh-action-pypi-publish and 2FA tokens:
Deploy to PyPI for GitHub releases.
Also deploy to TestPyPI for merges to `main`.
And add a release checklist.

Autodeploy to TestPyPI and to PyPI for GH releases

---

pyproject.toml

Since both the changelog and homepage are pointing to termcolor/termcolor, it would be weird to see the source located elsewhere.

Update source URL

---

src/termcolor/__init__.py
src/termcolor/termcolor.py
tests/test_termcolor.py

Re: https://github.com/hfeeki/termcolor/pull/3
`__ALL__` should be lowercase: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package
Let's deprecate the old one and remove it in the next major bump.
An up-to-date `__all__` is in `__init__.py`
---
Also convert a `%` formatting to f-string, and add module docstring.

Deprecate `__ALL__`, use `__all__` instead

---

.pre-commit-config.yaml
src/termcolor/termcolor.py
tests/test_termcolor.py
tox.ini

Fixes https://github.com/termcolor/termcolor/issues/2.
In the absence of special env vars, colour is enabled used when we're attached to a tty, that isn't a dumb terminal.
Normally we don't want to use colour for non-tty, like when piping output.
But GitHub Actions is also [not a tty](https://github.com/actions/runner/issues/241) and supports colour, so add support for `FORCE_COLOR`, which follows similar runes to [`NO_COLOR`](https://no-color.org/), to allow colour logging.

Support `FORCE_COLOR`

---

.github/workflows/test.yml
pyproject.toml
tox.ini

Currently in alpha 4, beta due in May, RC in July and final in October 2023.
* https://peps.python.org/pep-0693/

Add support for Python 3.12

---

src/termcolor/termcolor.py
tests/test_termcolor.py

Fixes https://github.com/termcolor/termcolor/issues/33, https://github.com/termcolor/termcolor/issues/28#issuecomment-1354537992, https://github.com/termcolor/termcolor/issues/2#issuecomment-1287010438.
https://no-color.org/ says (command-line) arguments should override the environment variables:
> 2. **How should configuration files and command-line arguments be processed in the presence of `$NO_COLOR`?**
>
> User-level configuration files and per-instance command-line arguments should override `$NO_COLOR`. A user should be able to export `$NO_COLOR` in their shell configuration file as a default, but configure a specific program in its configuration file to specifically enable color.
>
> This also means that software that can add color but doesn’t by default does not need to care about …

Add `no_color` and `force_color` parameters to override env vars

---

.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
tox.ini

Changes proposed in this pull request:
* Drop support for Python 3.7, EOL this month
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0537/
* Not planning a major bump, `requires-python = ">=3.8"` makes sure people get the right version

Drop support for EOL Python 3.7

---

pyproject.toml
src/termcolor/_types.py
src/termcolor/termcolor.py
tests/test_termcolor.py

This PR introduces two changes to the declared type signatures:
1. The allowed colors, highlights, and attributes are now checked against defined string literals. This means that, e.g., `cprint("hello", "orange")` will result in
```
error: Argument 2 to "cprint" has incompatible type "Literal['orange']"; expected "Optional[Literal['black', 'grey', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'light_grey', 'dark_grey', 'light_red', 'light_green', 'light_yellow', 'light_blue', 'light_magenta', 'light_cyan', 'white']]"
```
when using type checker.
2. The type of first argument of `colored` and `cprint` was relaxed to accept `object`s and not just `str`ings. This makes `cprint` more in line with `print`, which accepts arbitrary objects and fixes the example in README which reads …

Improve typing

---

src/termcolor/termcolor.py
tests/test_termcolor.py

- use `os.isatty(sys.stdout.fileno())` is much better than `sys.stdout.isatty()`
Fixed:
- #40 
- #41

Improve `isatty` check

---

.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
src/termcolor/termcolor.py
tests/test_termcolor.py
tox.ini

Python 3.8 is end-of-life next month:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0569/#lifespan

Drop support for Python 3.8

---

.github/workflows/deploy.yml
.pre-commit-config.yaml

PEP 740 ("Index support for digital attestations") introduces digital attestations which links the PyPI package to the GitHub repo, and helps users verify the source and authenticity of packages.
PyPI is still implementing support, but we can already start using it, which should also help them test out.
* https://peps.python.org/pep-0740/
* https://github.com/pypa/gh-action-pypi-publish#generating-and-uploading-attestations
* https://github.com/pypi/warehouse/issues/15871

Generate and upload attestations to PyPI

---

.github/workflows/lint.yml

Without cache: 1m 22s
https://github.com/hugovk/termcolor/actions/runs/11531229352/job/32101886048
With cache: 21s
https://github.com/hugovk/termcolor/actions/runs/11531229352/job/32101911080
Without cache: 48s
https://github.com/hugovk/termcolor/actions/runs/11532528002/job/32104427591
With cache: 15s
https://github.com/hugovk/termcolor/actions/runs/11532528002/job/32104447085

Lint with faster action-pre-commit-uv: 1m22s -> 48s and 21s -> 15s

---

.github/workflows/test.yml
pyproject.toml

3.14 is only at alpha 1, but I don't expect many if any incompatibilities, and if there are, it will be good to find it early.
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0745/

Add support for Python 3.14

---

.coveragerc
src/termcolor/termcolor.py
tests/test_termcolor.py

Speeds up imports when not running mypy.

Speedup: move typing imports into type-checking block

---

README.md
src/termcolor/termcolor.py
tests/test_termcolor.py

Similar to the CPython fix: https://github.com/python/cpython/issues/129061 / https://github.com/python/cpython/pull/129140
The `NO_COLOR` spec was changed in 2022:
> Tweak the spec wording to explain that it should be not empty
> "the presence of... when present" was redundant.
https://github.com/jcs/no_color/commit/99f90e27d0fac6a34d07998f8f577e1f2f620c61
It added "and not an empty string" and now reads:
> Command-line software which adds ANSI color to its output by default should check for a ``NO_COLOR`` environment variable that, when present and not an empty string (regardless of its value), prevents the addition of ANSI color.
https://no-color.org/
FORCE_COLOR has similar wording:
> Command-line software which outputs colored text should check for a FORCE_COLOR environment variable. …

Only apply `FORCE_COLOR`, `NO_COLOR` and `ANSI_COLORS_DISABLED` when present and not an empty string

---

pyproject.toml

Type hints were added in fb014068c2d7d967e40e95d92c0a33e2c97dc140 Adding the classifier helps advertise the status on PyPI.

Advertise typing via classifier

---

src/termcolor/termcolor.py
tests/test_termcolor.py

Caching the output of the lookups performed drops time from 3-5 milliseconds to hundreds of nanoseconds, as calls to `os.environ` and other system indicators are unlikely to change within the course of a running process.
Using the `cache` decorator allows for passing in `no_color/force_color` params to change the desired behavior, while allowing the text and colors to be different without increasing the cache size.
Resolves #48

Cache system lookups to save invocation time

---

pyproject.toml
tests/test_termcolor.py

Branch coverage exposed two conditions that were never untrue.
This happens if an invalid input type is passed, and the code currently returns the input + the reset value.

Test code branches

---

.gitignore
tests/test_termcolor.py
tox.ini

Run with:
uvx --with tox-uv tox -e mutmut
Enter interactive browsing with:
uvx --with tox-uv tox -e mutmut -- browse
Ref: https://mutmut.readthedocs.io/
Signed-off-by: Mike Fiedler <miketheman@gmail.com>

Add mutation testing
